/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf --transform 
Files: scene.gltf [9.85KB] > scene-transformed.glb [297.82KB] (-2924%)
Author: ALA (https://sketchfab.com/AlexisLarsonArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/heart-bab5e87d3da84efcaf8b62cbf2e4e730
Title: Heart
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { MeshBasicMaterial } from 'three'; // Import the MeshBasicMaterial

export default function Model(props) {
	const redMaterial = new MeshBasicMaterial({ color: 0xff0000 });

	const { nodes, materials } = useGLTF('./models/scene-transformed2.glb');
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Object_2.geometry} material={redMaterial} position={[-2, -2, 1]} scale={0.099} />
		</group>
	);
}

useGLTF.preload('./models/scene-transformed2.glb');
